# --- Site basics ---
title: Spike's Blog
tagline: Notes, graphics, and me yelling at compilers
description: A modern blog powered by Jekyll and Chirpy
url: "https://hersonrock.github.io"
baseurl: "/VoidPointer"  
lang: en_US
timezone: America/Bogota                

header:
  background: "/assets/img/background.jpg"
  background_color: "#f0f2f5"

# --- Theme & mode ---
theme: jekyll-theme-chirpy
theme_mode: auto                         

# --- Sidebar/Profile ---
avatar: /assets/img/avatar.jpg          
social:
  github: your-username
  twitter: ""
  linkedin: ""
  email: ""
  rss: /feed.xml

# --- Comments (we’ll wire this in Step 11) ---
comments:
  provider: false

# --- Analytics (Step 12) ---
analytics:
  provider: false
